pythonProject1/dmac/urls.py
from django.urls import path
from . import views
# from rest_framework import routers
# from .api import LeadViewSet
# from tableview import views

# router = routers.DefaultRouter()
# router.register('api/leads',LeadViewSet,'leads')

app_name = 'dmac'
urlpatterns = [
    path('login/', views.adminhome, name='adminhome'),
    path('', views.loginpage, name='glogin'),
    # path('logout/', views.logout, name='glogin'),
    # path('article/', views.article_list, name='glogin'),
    # path('tab_details/', views.tab_details, name='tab_details'),
    path('mergetable/', views.merge_table, name='mergetable'),
    path('post/', views.post, name='post'),
    path('rest/', views.rest, name='rest'),
    path('dmacpage/', views.dmacpage, name='dmacpage'),
    path('table/', views.Table, name ="table"),
    path('finaljson/', views.finaljson, name ="finaljson"),
    path('posttable/', views.posttable, name ="posttable"),
    path('postdata/', views.postdata, name ="postdata"),
    path('postdata1/', views.postdata1, name ="postdata1"),
    path('addtable/', views.addtable, name ="addtable"),
    path('postdata3/', views.postdata3, name ="postdata3"),
    path('concatdata/', views.concatdata, name ="concatdata"),
    path('concattable/', views.concattable, name ="concattable"),
    path('thankyou/', views.thankyou, name ="thankyou"),
    path('dragdrop/', views.dragdrop, name ="dragdrop"),
    path('tables/', views.tables, name='tables'),
    path('connections/', views.connections, name='connections'),
    # path('jsonreducer/', views.jsonreducer, name ="jsonreducer"),
    # path('save_json_to_table/', views.save_json_to_table, name ="save_json_to_table"),

]
#comment
# urlpatterns = router.urls

pythonProject1/pythonProject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dmac.urls')),
    # path('api/v1/', include('social_django.urls', namespace='social')),
]

pythonProject1/dmac/models.py
# from django.db import models

# Create your models here.
from django.db import models

class EmployeeEmails(models.Model):
    query_id = models.IntegerField(default=0, blank=True)
    table1 = models.CharField(max_length=300,null=True,blank=True)

    def __str__(self):
        return self.query_id

pythonProject1/dmac/views.py
from django.shortcuts import render,redirect
import pandas as pd
# import html5lib
# import requests
from sqlalchemy import create_engine

# from django.contrib.auth import login, logout, authenticate
# from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
# from django.core.mail import send_mail
from .models import EmployeeEmails
from django.conf import settings
# from django.contrib.auth import logout
import psycopg2
from iteration_utilities import unique_everseen
import json

# Create your views here.
#
# def glogin(request):
#     return render(request, 'dmac/index.html')

# Logout
# @login_required
# def logout_user(request):
#     logout(request)
#     return redirect('dmac:glogin')

# todo = [
#         {id: "01", name: "abhinav"},
#         {id: "02", name: "ashish"},
#         {id: "03", name: "ankit"},
#         {id: "04", name: "suresh"}
#     ]
# done = [
#     {id:"01",address:"rrrr"},
#     {id:"02",address:"tttt"},
#     {id:"03",address:"yyyy"},
#     {id:"04",address:"cvcvcv"}
#   ]
#  studentID=[
#     {id:"01",phone:"2344342"},
#     {id:"02",phone:"3434343"},
#     {id:"03",phone:"4334345"},
#     {id:"04",phone:"4545455"}
# ]
def loginpage(request):
    return render(request,'dmac/login.html')

# def logout(request):
#     loggout(request)
#     return redirect('dmac:loginpage')
# @login_required
def adminhome(request):
    print("this is my df dataframe!")
    # print(df1)
    todo = [
            {"id": "01", "name": "abhinav"},
            {"id": "02", "name": "ashish"},
            {"id": "03", "name": "ankit"},
            {"id": "04", "name": "suresh"}
        ]
    done = [
        {"id":"01","address":"rrrr"},
        {"id":"02","address":"tttt"},
        {"id":"03","address":"yyyy"},
        {"id":"04","address":"cvcvcv"}
      ]
    #  studentID=[
    #     {"id":"01","phone":"2344342"},
    #     {"id":"02","phone":"3434343"},
    #     {"id":"03","phone":"4334345"},
    #     {"id":"04","phone":"4545455"}
    # ]
    module_dict1 = [ "module 1", "module 2", "module 3"]
    # module_dict = {"0": "module x", "1": "module y", "2": "modulez"}
    # module_dict = json.dumps(module_dict)
    module_dict1 = json.dumps(module_dict1)
    try:
        engine = create_engine('postgresql://postgres:Programming1234@localhost:5432/postgres')
        df_aws2 = pd.read_sql_query("select relname from pg_class where relkind='r' and relname !~ '^(pg_|sql_)';", con=engine)
        tablename_list = list(df_aws2["relname"])
        module_dict = tablename_list
        module_dict11 = json.dumps(module_dict)
    except:
        tablename_list=["table1","table2","table3"]


    # data1=df_aws1.to_json(orient='records')

    print("Hello Hind this is your updated dataframe of D-mac")
    return render(request,'dmac/login-2.html',{'tablename_list':tablename_list,'module_dict1':module_dict1,'module_dict11':module_dict11})


def Table(request):
    todo = [
        {"id": "01", "name": "abhinav"},
        {"id": "02", "name": "ashish"},
        {"id": "03", "name": "ankit"},
        {"id": "04", "name": "suresh"}
    ]
    try:
        engine = create_engine('postgresql://postgres:Programming1234@localhost:5432/postgres')
        # # df1.to_sql('dmac', engine, if_exists='append')
        l1 = pd.read_sql_query('select * from "legacytable1"', con=engine)
        l2 = pd.read_sql_query('select * from "legacytable1"', con=engine)
        l3 = pd.read_sql_query('select * from "legacytable1"', con=engine)
        # Manipulate DataFrame using to_html() function
        table1 = l1.to_html()
        table2 = l2.to_html()
        table3 = l3.to_html()
    except:
        l1=pd.DataFrame(todo)
        table1 = l1.to_html()


    return HttpResponse(table1)


def merge_table(request):
    try:
        engine = create_engine('postgresql://postgres:Programming1234@localhost:5432/postgres')
        # l3.to_sql('legacytable3', engine,  if_exists='append')
        l1 = pd.read_sql_query('select * from "legacytable1"', con=engine)
        l2 = pd.read_sql_query('select * from "legacytable2"', con=engine)
        l3 = pd.read_sql_query('select * from "legacytable3"', con=engine)

        merg = pd.merge(l1, l2, on="Emp#", how="outer")
        merg1 = pd.merge(merg, l3, on="Emp#", how="outer")
        merg1["Full Name"] = merg1["First Name"] + "  " + merg1["Last Name"]

        def digit_tracker(x):
            d = str(x)
            k = len(d)
            spd = "0" * (11 - k) + d
            return spd

        merg1['uniqueid'] = merg1['Emp#'].apply(digit_tracker)
        final = merg1[["uniqueid", "Full Name", "Skills", "Technology", "Tax ID", "City", "Country Code", "Phone", "Email"]]
        final
        # final.to_sql('new_table', engine, if_exists='append')
        final.to_csv("new_table.csv")
        print("your new table is created and stored.")

        tablex = final.to_html()
    except:
        tablex="now you are not connected to database."


    return HttpResponse(tablex)


def finaljson(request):
    try:
        engine = create_engine('postgresql://postgres:Programming1234@localhost:5432/postgres')
        # l3.to_sql('legacytable3', engine,  if_exists='append')
        l1 = pd.read_sql_query('select * from "legacytable1"', con=engine)
        l2 = pd.read_sql_query('select * from "legacytable2"', con=engine)
        l3 = pd.read_sql_query('select * from "legacytable3"', con=engine)

        merg = pd.merge(l1, l2, on="Emp#", how="outer")
        merg1 = pd.merge(merg, l3, on="Emp#", how="outer")
        merg1["Full Name"] = merg1["First Name"] + "  " + merg1["Last Name"]

        def digit_tracker(x):
            d = str(x)
            k = len(d)
            spd = "0" * (11 - k) + d
            return spd

        merg1['uniqueid'] = merg1['Emp#'].apply(digit_tracker)
        final = merg1[["uniqueid", "Full Name", "Skills", "Technology", "Tax ID", "City", "Country Code", "Phone", "Email"]]
        final
        # final.to_sql('new_table', engine, if_exists='append')
        # final.to_csv("new_table.csv")
        print("your new table is created and stored.")
        mergedata1 = [
            {"id": "03", "name": "ankit"},
            {"id": "03", "address": "yyyy"},
            {"id": "02", "phone": "3434343"},
            {"id": "03", "phone": "23344"},
            {"id": "01", "address": "rrrr"},
        ]

        tablex = final.to_json(orient='records')
        # code for reshape json and remove redundancy
        plusdata=mergedata1
        print(plusdata)
        plusdata.sort(key=lambda item: item.get("id"))
        print(plusdata)
        for i in range(len(plusdata)-1):
            if (plusdata[i]["id"] == plusdata[i + 1]["id"]):
                plusdata[i].update(plusdata[i + 1])

        for i in range(len(plusdata)-1):
            if (plusdata[i]["id"] == plusdata[i + 1]["id"]):
                plusdata[i].update(plusdata[i + 1])
                plusdata[i + 1].update(plusdata[i])
        fitdata=list(unique_everseen(plusdata, key=lambda item: frozenset(item.items())))
        print(fitdata)
        return render(request, 'dmac/product.html', {'tablex': tablex, 'fitdata': fitdata})
    except:
        mergedata1 = [
            {"id": "03", "name": "ankit"},
            {"id": "03", "address": "yyyy"},
            {"id": "02", "phone": "3434343"},
            {"id": "03", "phone": "23344"},
            {"id": "01", "address": "rrrr"},
        ]

        # tablex = final.to_json(orient='records')
        # code for reshape json and remove redundancy
        plusdata = mergedata1
        print(plusdata)
        plusdata.sort(key=lambda item: item.get("id"))
        print(plusdata)
        for i in range(len(plusdata) - 1):
            if (plusdata[i]["id"] == plusdata[i + 1]["id"]):
                plusdata[i].update(plusdata[i + 1])

        for i in range(len(plusdata) - 1):
            if (plusdata[i]["id"] == plusdata[i + 1]["id"]):
                plusdata[i].update(plusdata[i + 1])
                plusdata[i + 1].update(plusdata[i])
        fitdata = list(unique_everseen(plusdata, key=lambda item: frozenset(item.items())))
        print(fitdata)
        return render(request, 'dmac/product.html', {'fitdata': fitdata})


def posttable(request):
    module_dict={"0": "module 1", "1": "module 2", "2": "module3"}
    try:
        engine = create_engine('postgresql://postgres:Programming123@localhost:5432/postgres')
        df_aws2 = pd.read_sql_query("select relname from pg_class where relkind='r' and relname !~ '^(pg_|sql_)';",con=engine)
        tablename_list = list(df_aws2["relname"])
    except:
        tablename_list = ['table1', 'table2','table3']
    return render(request,'dmac/posttable.html',{'tablename_list':tablename_list,'module_dict':module_dict})

def post(request):
    if request.method == "POST":
        table_name = request.POST.getlist('tablename')
        # table_name = json.loads(table_name.body)
    print(table_name)
    module_dict={"0": "module 1", "1": "module 2", "2": "module3"}
    try:
        engine = create_engine('postgresql://postgres:Programming123@localhost:5432/postgres')
        df_aws2 = pd.read_sql_query("select relname from pg_class where relkind='r' and relname !~ '^(pg_|sql_)';",con=engine)
        tablename_list = list(df_aws2["relname"])
    except:
        tablename_list = ['table1', 'table2','table3']

    try:

        mainvalues=[]
        maincolumns=[]
        colfunctionlist = []
        # for i in range(len(table_name)):
        #     l1 = pd.read_sql_query(f'select * from {table_name[i]}', con=engine)
        #     mkt = l1.iloc[0:, 1:]
        #     dataft = mkt.to_json(orient='records')
        #     s1 = json.loads(dataft)
        #     valuess1 = [list(x.values()) for x in s1]
        #     mainvalues.append(valuess1)
        #     columnss1 = [list(x.keys()) for x in s1][0]
        #     maincolumns.append(columnss1)


        for i in range(len(table_name)):

pythonProject1/dmac/templates/dmac/concat.html
<!DOCTYPE html>
<html>
<head>
<title>Drag and Drop Table Columns</title>
<style>
table {
    font-size: 11px;
    border-collapse:collapse;
    border:1px solid
}
table td, table th {
    border:1px solid;
    padding: 3px 5px 3px 5px;
}

.tableHead{
    background:#aaa;
    cursor:pointer
}

.draggedDiv {
    position:absolute;
    background:#eee;
}

.dragging {
    background:#eee;
    color:#000
}

.hovering {
    background:#ccc;
    color:#555
}
</style>
<script src='https://code.jquery.com/jquery-3.2.1.slim.js'
        integrity='sha256-tA8y0XqiwnpwmOIl3SGAcFl2RvxHjA8qp0+1uCGmRmg=' crossorigin='anonymous'></script>
<script>
// JQuery
$(function() {
    var heads = $("#tableOne th");

    $.each(heads, function(inx, row ) {
        var head = $(row);
        head.bind( "selectstart", function() { return false });
        head.bind( "mousedown", mousedown);
        head.bind( "mouseover", mouseover);
        head.bind( "mouseout", mouseout);
        head.bind( "mouseup", mouseup);

        head.addClass("tableHead");
    });
    $(document.documentElement).bind( "mouseup", documentMouseup);
    $(document.documentElement).bind( "mousemove", documentMouseMove);
});

function documentMouseup(ev){
    if (!dragTD) { return;}

    $(dragTD).removeClass("dragging");
    dragTD = null;
    draggedDiv.remove();
    draggedDiv = null;
}

function documentMouseMove(ev){
    if (!draggedDiv) { return;}

    draggedDiv.css({top: ev.pageY + 5 + "px", left: ev.pageX + 10 + "px"});
}

var dragTD = null, draggedDiv=null;
function mousedown(ev){
    dragTD = this;
    $(this).addClass("dragging");

    draggedDiv = $("<div>");
    draggedDiv.addClass("draggedDiv");
    draggedDiv.css({top: ev.pageY + 5 + "px", left:ev.pageX + 10 + "px"});
    $(document.documentElement).append(draggedDiv);

    var dragTable = $("<table>");
    draggedDiv.append(dragTable);

    var srcInx = dragTD.cellIndex;
    var rows = $("#tableOne tr");

    for (var x=0; x<rows.length; x++) {
        var tr = rows[x].cloneNode(false);
        dragTable.append(tr);
        var tds = rows[x].cells[srcInx].cloneNode(true);
        tr.appendChild(tds);
    }
}

function mouseover(ev){
    if (dragTD === null) { return;}
    $(this).addClass("hovering");
}

function mouseout(ev){
    if (dragTD === null) { return;}
    $(this).removeClass("hovering");
}

function mouseup(ev){
    $(this).removeClass("hovering");
    $(dragTD).removeClass("dragging");
    draggedDiv.remove();
    draggedDiv = null;

    var srcInx = dragTD.cellIndex;
    var tarInx = this.cellIndex;
    var rows = $("#tableOne tr");

    for (var x=0; x<rows.length; x++) {
        tds = rows[x].cells;
        rows[x].insertBefore(tds[srcInx], tds[tarInx])
    }

    dragTD = null;
}

</script>
</head>
<body>
<table id="tableOne">
    <thead>
        <tr>
            <th>Column 1</th>
            <th>Column 2</th>
            <th>Column 3</th>
            <th>Column 4</th>
            <th>Column 5</th>
            <th>Column 6</th>
            <th>Column 7</th>
            <th>Column 8</th>
            <th>Column 9</th>
            <th>Column 10</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>data 1</td>
            <td>data 2</td>
            <td>data 3</td>
            <td>data 4</td>
            <td>data 5</td>
            <td>data 6</td>
            <td>data 7</td>
            <td>data 8</td>
            <td>data 9</td>
            <td>data 10</td>
        </tr>
        <tr>
            <td>data 1</td>
            <td>data 2</td>
            <td>data 3</td>
            <td>data 4</td>
            <td>data 5</td>
            <td>data 6</td>
            <td>data 7</td>
            <td>data 8</td>
            <td>data 9</td>
            <td>data 10</td>
        </tr>
    </tbody>
</table>

</body>
</html>

pythonProject1/dmac/templates/dmac/dmac.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {
  background-image: url('https://bccs.tech/wp-content/uploads/2020/05/SAP-Kicks-Off-First-SAP.jpg');
}
table {
  font-family: arial, sans-serif;
  width: auto;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 0px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}

.dropdown {
  float: center;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 30px;
  border: none;
  outline: none;
  color: white;
  padding: auto;
  background-color: black;
  font: inherit;
  margin: 0px;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  width: auto;
  left: 0;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.1);
  z-index: 4;
}

.dropdown-content .header {
  background: black;
  padding: 5PX;
  color: white;
}

.dropdown:hover .dropdown-content {
  display: block;
}

/* Create three equal columns that floats next to each other */
.column {
  float: left;
  width: auto;
  padding: 10px;
  background-color: #ccc;
  height: inherit;
}

.column a {
  float: none;
  color: black;
  padding: 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.column a:hover {
  background-color: #ddd;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

#draggable {
  width: 50%;
  height: auto;
  text-align: center;
  background: inherit;
}

.dropzone {
  width: 100%;
  height: 100%;
  background: inherit;
  margin-bottom: 100px;
  padding: auto;
}
* {
  box-sizing: border-box;
}
.menu {
  float:left;
  width:20%;
  text-align:center;
}
.menu a {
  background-color:#000000;
  padding:8px;
  margin-top:7px;
  display:block;
  width:100%;
  color:White;
}
.main {
  background-color:#ffffff;
  float:left;
  width:60%;
  padding:0px 20px;
  color:Black;
}
.right {
  background-color:#000000;
  float:left;
  width:20%;
  padding:15px;
  margin-top:7px;
  text-align:center;
}

@media only screen and (max-width:620px) {
  /* For mobile phones: */
  .menu, .main, .right {
    width:100%;
  }
}
</style>
<script> var dragged;

/* events fired on the draggable target */
document.addEventListener("drag", function(event) {

}, false);

document.addEventListener("dragstart", function(event) {
  // store a ref. on the dragged elem
  dragged = event.target;
  // make it half transparent
  event.target.style.opacity = .5;
}, false);

document.addEventListener("dragend", function(event) {
  // reset the transparency
  event.target.style.opacity = "";
}, false);

/* events fired on the drop targets */
document.addEventListener("dragover", function(event) {
  // prevent default to allow drop
  event.preventDefault();
}, false);

document.addEventListener("dragenter", function(event) {
  // highlight potential drop target when the draggable element enters it
  if (event.target.className == "dropzone") {
    event.target.style.background = "purple";
  }

}, false);

document.addEventListener("dragleave", function(event) {
  // reset background of potential drop target when the draggable element leaves it
  if (event.target.className == "dropzone") {
    event.target.style.background = "";
  }

}, false);

document.addEventListener("drop", function(event) {
  // prevent default action (open as link for some elements)
  event.preventDefault();
  // move dragged elem to the selected drop target
  if (event.target.className == "dropzone") {
    event.target.style.background = "";
    dragged.parentNode.removeChild( dragged );
    event.target.appendChild( dragged );
  }
}, false);
</script>
</head>
<body style="font-family:Verdana;color:#aaaaaa;">

<div style="background-color:#000000;padding:15px;text-align:center;">
  <h1>WELCOME TO DMAC </h1>
</div>

<div style="overflow:auto">
  <div class="menu"><div class="dropdown">
    <button class="dropbtn">Check your Table
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <div class="header">
        <h4>Table Names</h4>
      </div>   
      <div class="row">
        <div class="column" style="overflow:auto; height:500px">
          <h3>Category 1</h3>
          {% for i in tablename_list %}
          <a href="#">{{ i }}</a>
          {% endfor %}

        </div>

      </div>
    </div>
</div></div>
<div class="main">
    <h2>MAIN CONTENT</h2>
    <div class="dropzone"><div id="draggable" draggable="true" ondragstart="event.dataTransfer.setData('twxt/plain',null)"><table>
    <tr>
    <th>Company</th>
    <th>Contact</th>
    <th>Country</th>
  </tr>
  <tr>
    <td>Alfreds Futterkiste</td>
    <td>Maria Anders</td>
    <td>Germany</td>
  </tr>
  <tr>
    <td>Centro comercial Moctezuma</td>
    <td>Francisco Chang</td>
    <td>Mexico</td>
  </tr>
  <tr>
    <td>Ernst Handel</td>
    <td>Roland Mendel</td>
    <td>Austria</td>
  </tr>
  <tr>
    <td>Island Trading</td>
    <td>Helen Bennett</td>
    <td>UK</td>
  </tr>
  <tr>
    <td>Laughing Bacchus Winecellars</td>
    <td>Yoshi Tannamuri</td>
    <td>Canada</td>
  </tr>
  <tr>
    <td>Magazzini Alimentari Riuniti</td>
    <td>Giovanni Rovelli</td>
    <td>Italy</td>
  </tr>
</table></div></div>
  </div>
  <div class="right">
    <h2>About</h2>
    <p>Dmac tables and its data are handled, Updated and Updated by Mckinsol Consulting Inc.</p>
  </div>
</div>

<div style="background-color:#000000;text-align:center; padding:10px; margin-top:240px;">© copyright mckinsol.com</div>

</body>
</html>

pythonProject1/dmac/templates/dmac/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>DMac</title>

  <style>
*{
  padding: 0%;
  margin: 0%;
  box-sizing: border-box;
}
.d-block{
  width: 100%;
  height: 350px;
}
body{
  display: flex;
  flex-direction: column;
  height: 100vh;
  background-color: rgb(46, 194, 162);
}
.btn{
  height: 70px;
  width: 300px;
  margin-top: 100px;
  
}
a{
  text-decoration: none;
  font-weight: 800;
  color: white;
}
.page-footer{
  background-color: #333;
  margin-top: auto;
  
}
.footer-copyright{
  color: white;
}

  </style>
  </head>
  <body>
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="/static/img/dmacbanner.jpg" class="d-block" alt="dmac">
          <div class="carousel-caption d-none d-md-block">
            
            <p class="text-dark">Data Migration Agile Connector</p>
          </div>
        </div>
      </div>
      
    </div>
  
 
           <center>
              <a href="{% url 'dmac:posttable' %}" class="login-btn uk-flex uk-flex-center uk-flex-middle">
                <span uk-icon="google" class="uk-margin-right"></span><button type="button" class="btn btn-primary">LOGIN</button></a>
              
           </center>
           <!-- Footer -->
<footer class="page-footer">

  
  <!-- Copyright -->
  <div class="footer-copyright text-center py-2">© 2021 Copyright:
    <a href="#">DMAC</a>
  </div>

  <!-- Copyright -->

</footer>
<!-- Footer -->
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

pythonProject1/dmac/templates/dmac/login.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'adminboard/css/login.css' %}">
{% endblock %}

{% block body %}
  <div class="w-full relative overflow-hidden h-screen flex">
    <div class="polygon-hero absolute">
    </div>
    <div class="polygon-page relative border border-solid border-suvaGrey rounded-lg md:rounded-none px-4 py-4 md:border-0 flex flex-col justify-center md:w-3/5 lg:py-8 lg:pl-8 lg:pr-10 bg-no-repeat">
      <div class="absolute top-8 left-8">
        <img src="{% static 'img/mckinsol-logo.png' %}" alt="logo" class="w-36 h-12 md:w-72 md:h-24">
      </div>
      <div class="z-10">
        <h3 class="text-7xl md:text-9xl font-bold w-3/4 text-gray-800 font-serif">DMAC</h3>
        <p class="text-lg md:text-2xl md:tracking-widest font-semibold">Data Migration Agile Connector</p>
        <a href="{% url 'dmac:posttable' %}" class="inline-flex px-4 py-3 items-center bg-indigo-600 text-white text-base md:text-lg rounded-lg mt-4">Sign in with Google</a>
      </div>
      <footer class="absolute bottom-8 left-8 font-semibold text-sm md:text-base">
        <span>&copy; 2021 Copyright: </span>
        <span class="text-green-600">McKinsol Consulting Inc.</span>
      </footer>
    </div>
  <div>
{% endblock %}